const { copyFile } = require('../../utils');
const {
  DRAWER_INDEX,
  DRAWER_MENU_INDEX,
  DRAWER_MENU_STYLES,
  DRAWER_MENU_LAYOUT,
  DRAWER_OVERLAY_INDEX,
  DRAWER_OVERLAY_STYLES,
  DRAWER_REDUX_ACTIONS,
  DRAWER_REDUX_REDUCER
} = require('../../files');

const FILES = [
  DRAWER_INDEX,
  DRAWER_MENU_INDEX,
  DRAWER_MENU_STYLES,
  DRAWER_MENU_LAYOUT,
  DRAWER_OVERLAY_INDEX,
  DRAWER_OVERLAY_STYLES,
  DRAWER_REDUX_ACTIONS,
  DRAWER_REDUX_REDUCER
];

module.exports = function drawerFeatureFiles() {
  FILES.forEach(copyFile.bind(this));
};
