/* eslint-disable id-length */
const { copyFile } = require('../../utils');
const {
  ONBOARDING,
  ONBOARDING_I18N,
  ONBOARDING_FOOTER,
  ONBOARDING_FOOTER_STYLES,
  ONBOARDING_FOOTER_BUTTONS_INFO,
  ONBOARDING_FIRST_SCREEN,
  ONBOARDING_FIRST_SCREEN_STYLES,
  ONBOARDING_SECOND_SCREEN,
  ONBOARDING_SECOND_SCREEN_STYLES,
  ONBOARDING_THIRD_SCREEN,
  ONBOARDING_THIRD_SCREEN_STYLES,
  ONBOARDING_SWIPER_SCREEN,
  ONBOARDING_SWIPER_SCREEN_STYLES,
  ONBOARDING_SWIPER_SCREENS,
  INITIAL_LOADING_SERVICE
} = require('../../files');

const FILES = [
  ONBOARDING,
  ONBOARDING_I18N,
  ONBOARDING_FOOTER,
  ONBOARDING_FOOTER_STYLES,
  ONBOARDING_FOOTER_BUTTONS_INFO,
  ONBOARDING_FIRST_SCREEN,
  ONBOARDING_FIRST_SCREEN_STYLES,
  ONBOARDING_SECOND_SCREEN,
  ONBOARDING_SECOND_SCREEN_STYLES,
  ONBOARDING_THIRD_SCREEN,
  ONBOARDING_THIRD_SCREEN_STYLES,
  ONBOARDING_SWIPER_SCREEN,
  ONBOARDING_SWIPER_SCREEN_STYLES,
  ONBOARDING_SWIPER_SCREENS,
  INITIAL_LOADING_SERVICE
];

module.exports = function onBoardingFeatureFiles() {
  FILES.forEach(copyFile.bind(this));
};
